import {useCallback,useEffect,useRef,useState} from 'react';
import {CalendarCheck,CalendarDays,BookOpen,Files,Archive,Settings as SettingsIcon,Search,Plus,ChevronLeft,ChevronRight,ArrowRight,ArrowUpRight,Flag,FileText,Copy,Link as LinkIcon,MoreHorizontal,Check,WifiOff,X,PanelRightClose,LogOut,Sun,Moon,RefreshCw,Clock,CheckCircle2,Pencil,Trash2,Leaf,Menu} from 'lucide-react';
import {api,ApiError,isLocalApp,nativeAction,type Account,type Appearance,type StudyRecord,type Data,type Subject,type Debt,type Task,type Lesson,type Note,type Occurrence,type LessonException} from '@semestr/api-client';
import {labels,dateLabel,localDate,typed,activeDebt,activeTask,contextText,sortSubjects} from './utils';
import {demoAccount,demoRecords} from './demo';
import Auth from './Auth';
import Editor,{Dialog} from './Editor';
import Settings from './Settings';
import Week from './Week';
import LessonBadge from './LessonBadge';
import RequirementsCard from './RequirementsCard';
import {readPreference,writePreference,clearDrafts} from './storage';

type View='today'|'week'|'subjects'|'debts'|'archive'|'settings';
const navigation=[{id:'today',label:'Сегодня',icon:CalendarCheck},{id:'week',label:'Неделя',icon:CalendarDays},{id:'subjects',label:'Предметы',icon:BookOpen},{id:'debts',label:'Долги',icon:Files},{id:'archive',label:'Архив',icon:Archive}] as const;
const headings:Record<View,[string,string]>={today:['Всё успеется','Одна пара. Одно дело. Один шаг за раз.'],week:['Неделя в деталях','Оставьте место не только для учёбы.'],subjects:['Каждому — своё место','Предметы и всё, что с ними связано.'],debts:['Закрыть и выдохнуть','Академическая разница и задолженности'],archive:['Уже позади','Здесь живут ваши маленькие и большие победы.'],settings:['Так, как вам удобно','Ваш профиль и пространство для учёбы.']};
export default function App(){
 const[demo,setDemo]=useState(new URLSearchParams(location.search).has('demo'));const[account,setAccount]=useState<Account|null>(demo?demoAccount:null);const[initial,setInitial]=useState(!demo);const[loading,setLoading]=useState(false);const[records,setRecords]=useState<StudyRecord[]>(demo?demoRecords:[]);const[occurrences,setOccurrences]=useState<Occurrence[]>([]);const[exceptions,setExceptions]=useState<LessonException[]>([]);const[view,setView]=useState<View>('debts');const[selected,setSelected]=useState<string|null>(demo?'subject-2':null);const[detailOpen,setDetailOpen]=useState(false);const[tab,setTab]=useState('context');const[search,setSearch]=useState('');const[notice,setNotice]=useState('');const[connection,setConnection]=useState('');const[editor,setEditor]=useState<{kind:Data['kind'];existing?:StudyRecord}|null>(null);const[confirmDelete,setConfirmDelete]=useState<StudyRecord|null>(null);const[move,setMove]=useState<Occurrence|null>(null);const[anchor,setAnchor]=useState(new Date());const[theme,setTheme]=useState(readPreference('semestr:theme','light'));const[menu,setMenu]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme;writePreference('semestr:theme',theme)},[theme]);
 const notify=useCallback((s:string)=>setNotice(s),[]);
 const appearanceReady=useRef(false);
 async function changeTheme(value:string){try{if(isLocalApp&&!demo)await api.request('/appearance','PUT',{theme:value});setTheme(value)}catch(e){notify((e as Error).message)}}
 useEffect(()=>{if(!isLocalApp)return;const add=()=>setEditor({kind:'subject'});const exportData=()=>{void nativeAction<{saved:boolean}>('export').then(r=>{if(r.saved)notify('Экспорт сохранён')}).catch(e=>notify(e.message))};window.addEventListener('semestr:new-subject',add);window.addEventListener('semestr:export',exportData);return()=>{window.removeEventListener('semestr:new-subject',add);window.removeEventListener('semestr:export',exportData)}},[notify]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(t)},[notice]);
 const refresh=useCallback(async()=>{if(demo)return;try{const s=await api.session();if(isLocalApp&&!appearanceReady.current){const theme=readPreference('semestr:theme','light');const appearance=await api.request<Appearance>('/appearance/initialize','POST',{theme:theme==='dark'?'dark':'light'});appearanceReady.current=true;setTheme(appearance.theme)}const rs=await api.records();setAccount(s.account);setRecords(rs);setSelected(prev=>prev&&rs.some(r=>r.id===prev)?prev:rs.find(r=>r.data.kind==='subject')?.id||null);setConnection('')}catch(e){if(e instanceof ApiError&&e.status===401){setAccount(null);setRecords([])}else setConnection((e as Error).message)}finally{setInitial(false);setLoading(false)}},[demo]);
 useEffect(()=>{if(demo)return;void refresh();const poll=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},20000);const visibility=()=>{if(document.visibilityState==='visible')void refresh()};window.addEventListener('online',visibility);document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(poll);window.removeEventListener('online',visibility);document.removeEventListener('visibilitychange',visibility)}},[refresh]);
 useEffect(()=>{const host=window as Window&{semestrPendingSubject?:string};const show=(e:Event)=>{const id=(e as CustomEvent<string>).detail;if(typeof id==='string'){delete host.semestrPendingSubject;setSelected(id);setView('subjects');setTab('context');setDetailOpen(true)}};window.addEventListener('semestr:show-subject',show);if(host.semestrPendingSubject)show(new CustomEvent('semestr:show-subject',{detail:host.semestrPendingSubject}));return()=>window.removeEventListener('semestr:show-subject',show)},[]);
 const loadSchedule=useCallback(async()=>{if(demo||!account)return;const from=new Date(anchor);from.setDate(from.getDate()-8);from.setHours(0,0,0,0);const until=new Date(from);until.setDate(until.getDate()+18);try{const [s,e]=await Promise.all([api.schedule(from,until),api.request<LessonException[]>('/schedule/exceptions')]);setOccurrences(s);setExceptions(e)}catch(e){setConnection((e as Error).message)}},[demo,account?.id,anchor]);
 useEffect(()=>{void loadSchedule()},[loadSchedule,records]);
 const subjects=sortSubjects(typed<Subject>(records,'subject'));const debts=typed<Debt>(records,'debt');const tasks=typed<Task>(records,'task');const activeDebts=debts.filter(activeDebt);const differenceSubjectIds=new Set(debts.filter(d=>d.data.reason==='difference').map(d=>d.data.subjectId));const activeSubjects=subjects.filter(s=>s.data.status!=='closed'&&!differenceSubjectIds.has(s.id));const subject=subjects.find(s=>s.id===selected);const related=records.filter(r=>'subjectId'in r.data&&r.data.subjectId===selected);const subjectDebts=typed<Debt>(related,'debt');const subjectTasks=typed<Task>(related,'task');const subjectLessons=typed<Lesson>(related,'lesson');const zone=account?.profile.timezone||'Europe/Moscow';
 useEffect(()=>{if(account?.profile.timezone){const date=new Intl.DateTimeFormat('en-CA',{timeZone:account.profile.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());setAnchor(new Date(date+'T12:00:00'))}},[account?.profile.timezone]);
 const dayKey=(s:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(s));
 const time=(s:string)=>new Intl.DateTimeFormat('ru',{hour:'2-digit',minute:'2-digit',timeZone:zone}).format(new Date(s));
 const monday=new Date(anchor);monday.setDate(anchor.getDate()-((anchor.getDay()+6)%7));const days=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(d.getDate()+i);return d});
 function openEditor(kind:Data['kind'],existing?:StudyRecord){if(demo){notify('Это деморежим. Создайте аккаунт, чтобы сохранять свои данные.');return}setEditor({kind,existing})}
 function choose(id:string){setSelected(id);setDetailOpen(true)}
 function enterDemo(){history.replaceState(null,'','?demo=1');setDemo(true);setAccount(demoAccount);setRecords(demoRecords);setSelected('subject-2');setInitial(false)}
 function leaveDemo(){history.replaceState(null,'',location.pathname);setDemo(false);setAccount(null);setRecords([]);setSelected(null);setInitial(true)}
 async function logout(){try{await api.request('/auth/logout','POST');if(account)clearDrafts(account.id);setAccount(null);setRecords([])}catch(e){notify((e as Error).message)}}
 async function copyContext(){if(!subject)return;try{const value=contextText(subject.data,related);if(isLocalApp)await nativeAction('copy',{text:value});else await navigator.clipboard.writeText(value);notify('Контекст скопирован. Можно вставить его в ChatGPT или Codex.')}catch{notify('Не удалось скопировать текст. Попробуйте ещё раз.')}}
 async function restoreException(e:LessonException){try{await api.request(`/schedule/exceptions/${e.id}?version=${e.version}`,'DELETE');notify('Занятие восстановлено по расписанию');void loadSchedule()}catch(err){notify((err as Error).message)}}
 async function remove(){if(!confirmDelete)return;try{await api.request(`/records/${confirmDelete.id}?version=${confirmDelete.version}`,'DELETE');setConfirmDelete(null);notify('Запись удалена');void refresh()}catch(e){notify((e as Error).message)}}
 const match=(s:Subject)=>`${s.title} ${s.teacher}`.toLocaleLowerCase().includes(search.toLocaleLowerCase());
 function empty(title:string,description:string,action?:()=>void){return <div className="empty-state"><BookOpen size={34} strokeWidth={1}/><h3>{title}</h3><p>{description}</p>{action&&<button className="outline" onClick={action}><Plus size={16}/> Добавить</button>}</div>}
 function debtRows(list:StudyRecord<Debt>[]){const visible=list.filter(d=>{const s=subjects.find(s=>s.id===d.data.subjectId);return s&&match(s.data)}).sort((a,b)=>(a.data.deadline||'9999').localeCompare(b.data.deadline||'9999'));const groups=[...new Set(visible.map(d=>d.data.deadline))];return visible.length?groups.map(deadline=><section className="debt-group" key={deadline||'none'}><div className="folder-label"><span>{deadline?'ДО '+dateLabel(deadline):'СРОК НЕ УТОЧНЁН'}</span><span>{visible.filter(d=>d.data.deadline===deadline).length}</span></div>{visible.filter(d=>d.data.deadline===deadline).map(d=>{const s=subjects.find(s=>s.id===d.data.subjectId)!;return <div role="button" tabIndex={0} aria-label={s.data.title} className={'subject-row '+(selected===s.id?'selected':'')} onClick={()=>choose(s.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(s.id)}}} key={d.id}><span className="row-number">{String(visible.indexOf(d)+1).padStart(2,'0')}</span><div className="row-copy"><h3>{s.data.title}</h3><p>{d.data.teacher||s.data.teacher||'Преподаватель не уточнён'}</p>{d.data.nextStep&&<span className="next-step"><ArrowRight size={12}/>{d.data.nextStep}</span>}</div><button className={'status-tag '+d.data.status} onClick={e=>{e.stopPropagation();openEditor('debt',d)}}><FileText size={15}/><span>{labels[d.data.status]}</span></button></div>})}</section>):empty(view==='archive'?'История только начинается':'Можно выдохнуть',search?'По этому запросу ничего не найдено.':'Здесь пока нет академических долгов.',()=>openEditor('debt'))}
 function taskRow(t:StudyRecord<Task>){return <div className={'task-row '+(t.data.status==='accepted'?'done':'')} key={t.id}><button className="task-dot" aria-label="Изменить статус задания" onClick={()=>openEditor('task',t)}>{t.data.status==='accepted'?<Check size={14}/>:<span/>}</button><button className="task-title" onClick={()=>openEditor('task',t)}><strong>{t.data.title}</strong><span>{labels[t.data.status]}{t.data.deadline?' · '+dateLabel(t.data.deadline,zone):''}</span></button></div>}
 if(initial)return <div className="boot"><span className="brand">Семестр</span><p>Открываем ваше пространство…</p>{connection&&<><div className="error">{connection}</div><button onClick={()=>{setInitial(false)}}>Перейти ко входу</button></>}</div>;
 if(!account&&isLocalApp)return <div className="boot"><span className="brand">Семестр</span><p>Не удалось открыть локальные данные.</p><div className="error" role="alert">{connection}</div><button className="outline" onClick={()=>{setInitial(true);void refresh()}}>Повторить</button></div>;
 if(!account)return <Auth serverError={connection} onRetry={()=>void refresh()} onLogin={a=>{setAccount(a);setLoading(true);void refresh()}} onDemo={enterDemo}/>;
 return <div className="app-shell"><aside className={'sidebar '+(menu?'expanded':'')}><div className="window-dots" aria-hidden="true"><i/><i/><i/></div><a className="brand" href="#" onClick={e=>{e.preventDefault();setView('today')}}>Семестр<span className="brand-mark">✳</span></a><p className="workspace-name">{account.profile.university||'Ваше пространство'}{account.profile.group?' · '+account.profile.group:''}</p><span className="nav-caption">МОЯ УЧЁБА</span><nav>{navigation.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>{setView(n.id);setMenu(false);setDetailOpen(false);setSearch('')}}><n.icon size={20} strokeWidth={1.4}/><span>{n.label}</span>{n.id==='debts'&&activeDebts.length>0&&<b>{activeDebts.length}</b>}</button>)}</nav><div className="sidebar-bottom"><div className="semester-note"><Leaf size={18}/><span>{account.profile.semester||'Ваш семестр'}<small>В своём ритме</small></span></div><button className={view==='settings'?'active':''} onClick={()=>{setView('settings');setDetailOpen(false);setMenu(false)}}><SettingsIcon size={20} strokeWidth={1.4}/><span>Настройки</span></button><div className="profile-badge"><span>{(account.profile.name||'С')[0]}</span><div>{account.profile.name||'Студент'}<small>{demo?'Демопространство':isLocalApp?'На этом Mac':'Личное пространство'}</small></div>{!isLocalApp&&<button className="icon-button" title={demo?'Войти в аккаунт':'Выйти'} onClick={()=>demo?leaveDemo():void logout()}><LogOut size={17}/></button>}</div></div></aside>
 <div className="workspace"><header className="toolbar"><button className="mobile-menu icon-button" aria-label="Открыть навигацию" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><div className="search"><Search size={18}/><input aria-label="Найти предмет" placeholder="Найти предмет…" value={search} onChange={e=>{setSearch(e.target.value);if(!['debts','subjects','archive'].includes(view))setView('subjects')}}/><kbd>⌕</kbd></div><button className="icon-button refresh" title="Обновить данные" onClick={()=>{setLoading(true);if(demo){setLoading(false);notify('Вы смотрите демопространство')}else void refresh()}}><RefreshCw size={17} className={loading?'spin':''}/></button><details className="add-menu"><summary className="outline"><Plus size={18}/><span>Добавить</span></summary><div>{(['subject','task','debt','lesson','note'] as const).map(k=><button key={k} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');openEditor(k)}}>{{subject:'Предмет',task:'Задание',debt:'Академический долг',lesson:'Занятие',note:'Заметка'}[k]}</button>)}</div></details></header>
 {demo&&<div className="demo-banner"><span>Знакомимся с «Семестром» <span className="optional">· Вымышленные данные, просмотр без сохранения</span></span><button onClick={leaveDemo}>Создать своё пространство <ArrowUpRight size={14}/></button></div>}{connection&&<div className="connection-banner" role="alert"><WifiOff size={17}/>{connection}<button onClick={()=>void refresh()}>Повторить</button></div>}
 <main><div className="page-heading"><span className="eyebrow">{view==='debts'?'С ЧИСТОГО ЛИСТА':account.profile.semester||'ВАШ СЕМЕСТР'}</span><h1>{headings[view][0]}</h1><p>{headings[view][1]}</p></div>
 {view!=='settings'&&<div className="date-strip"><div className="month-control"><button onClick={()=>setAnchor(new Date())}>{new Intl.DateTimeFormat('ru',{month:'long',year:'numeric'}).format(anchor).replace(' г.','')}</button><div><button className="icon-button" aria-label="Предыдущая неделя" onClick={()=>setAnchor(new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()-7))}><ChevronLeft size={15}/></button><button className="icon-button" aria-label="Следующая неделя" onClick={()=>setAnchor(new Date(anchor.getFullYear(),anchor.getMonth(),anchor.getDate()+7))}><ChevronRight size={15}/></button></div></div><div className="days">{days.map(d=><button key={localDate(d)} className={localDate(d)===localDate(anchor)?'selected':''} onClick={()=>{setAnchor(d);if(view!=='week')setView('today')}}><span>{new Intl.DateTimeFormat('ru',{weekday:'short'}).format(d)}</span><strong>{d.getDate()}</strong><span className="day-lesson-marks">{['practice','lecture','lab'].filter(type=>occurrences.some(o=>o.type===type&&dayKey(o.startsAt)===localDate(d))).map(type=><i key={type} className={'lesson-'+type} title={labels[type]} aria-label={labels[type]}/>)}</span></button>)}</div></div>}
 {!account.profile.onboarded&&!demo&&<div className="onboarding"><div><span className="eyebrow">ПЕРВЫЙ ШАГ</span><h3>Устроимся поудобнее</h3><p>Укажите часовой пояс и семестр. Потом добавьте первый предмет.</p></div><button className="primary" onClick={()=>setView('settings')}>Настроить <ArrowRight size={16}/></button></div>}
 {view==='debts'&&<>{debtRows(activeDebts)}{activeDebts.length>0&&<div className="next-card"><div className="flag-icon"><Flag size={25} strokeWidth={1.5}/></div><div><span className="eyebrow">БЛИЖАЙШИЙ ШАГ</span><h3>{(subjectDebts.find(activeDebt)||activeDebts[0]).data.nextStep||'Уточнить требования к сдаче'}</h3></div><button className="outline" onClick={()=>{choose((subjectDebts.find(activeDebt)||activeDebts[0]).data.subjectId);setTab('context')}}>Открыть контекст <ArrowRight size={16}/></button></div>}<p className="quiet-note">Большие дела закрываются маленькими шагами.</p></>}
 {view==='subjects'&&<><div className="section-top"><span>{activeSubjects.length} предметов в этом семестре</span><button className="text-button" onClick={()=>openEditor('subject')}><Plus size={16}/> Новый предмет</button></div>{activeSubjects.filter(s=>match(s.data)).map((s,i)=><button key={s.id} className={'subject-row full-row '+(selected===s.id?'selected':'')} onClick={()=>choose(s.id)}><span className="row-number">{String(i+1).padStart(2,'0')}</span><div className="row-copy"><h3>{s.data.title}</h3><p>{s.data.teacher||'Преподаватель не уточнён'}</p><span className="next-step">{tasks.filter(t=>t.data.subjectId===s.id&&activeTask(t)).length} открытых заданий</span></div><span className="status-tag">{labels[s.data.assessment]}</span></button>)}{!activeSubjects.filter(s=>match(s.data)).length&&empty('С чего начнём?',search?'Попробуйте другой запрос.':'Добавьте первый предмет. Расписание можно заполнить позже.',()=>openEditor('subject'))}</>}
 {view==='today'&&<><div className="section-top"><h2>Ближайшие пары</h2><span>{zone}</span></div>{occurrences.filter(o=>dayKey(o.startsAt)===localDate(anchor)).map(o=><div className={'lesson-card lesson-'+o.type} key={o.lessonId+o.originalDate}><div className="lesson-time">{time(o.startsAt)}<span>{time(o.endsAt)}</span></div><div><button className="plain" onClick={()=>choose(o.subjectId)}><h3>{o.title}</h3></button><p><LessonBadge type={o.type}/>{o.room?' · '+o.room:''}{o.changed?' · Перенесено':''}</p>{o.conflict&&<span className="conflict">Пересечение занятий</span>}</div><div className="lesson-actions">{o.onlineUrl?<a className="primary" href={o.onlineUrl} target="_blank" rel="noreferrer">Подключиться <ArrowUpRight size={16}/></a>:<span className="muted small">Нет ссылки</span>}<button className="text-button" onClick={()=>setMove(o)}>Перенести / отменить</button></div></div>)}{!occurrences.some(o=>dayKey(o.startsAt)===localDate(anchor))&&empty('День без пар','Можно заняться заданиями или немного отдохнуть.',()=>openEditor('lesson'))}<div className="section-top"><h2>Задания и дедлайны</h2><button className="text-button" onClick={()=>openEditor('task')}><Plus size={16}/> Задание</button></div>{tasks.filter(activeTask).sort((a,b)=>(a.data.deadline||'9999').localeCompare(b.data.deadline||'9999')).map(taskRow)}{!tasks.some(activeTask)&&<p className="muted">Пока всё спокойно — открытых заданий нет.</p>}{activeDebts.length>0&&<><div className="section-top"><h2>Следующие шаги</h2></div>{activeDebts.map(d=><button className="action-row" key={d.id} onClick={()=>{choose(d.data.subjectId);setTab('context')}}><Flag size={17}/><span>{d.data.nextStep||'Уточнить требования'}<small>{subjects.find(s=>s.id===d.data.subjectId)?.data.title}</small></span><ArrowRight size={16}/></button>)}</>}</>}
 {view==='week'&&<><div className="section-top"><span>{zone}</span><button className="text-button" onClick={()=>openEditor('lesson')}><Plus size={16}/> Занятие</button></div><Week days={days} occurrences={occurrences} tasks={tasks} timezone={zone} onLesson={setMove} onTask={t=>openEditor('task',t)}/><p className="quiet-note">Нажмите на занятие, чтобы перенести или отменить только эту пару.</p></>}
 {view==='archive'&&<><div className="section-top"><h2>Закрытые долги</h2><CheckCircle2 size={22}/></div>{debtRows(debts.filter(d=>!activeDebt(d)))}<div className="section-top"><h2>Завершённые предметы</h2></div>{subjects.filter(s=>s.data.status==='closed'&&match(s.data)).map(s=><button className="action-row" key={s.id} onClick={()=>choose(s.id)}><CheckCircle2 size={18}/>{s.data.title}<ArrowRight size={16}/></button>)}{!subjects.some(s=>s.data.status==='closed')&&<p className="muted">Закрытый предмет появится здесь.</p>}</>}
 {view==='settings'&&<Settings account={account} demo={demo} theme={theme} onTheme={value=>void changeTheme(value)} onRefresh={()=>void refresh()} notify={notify} onLogout={()=>{setAccount(null);setRecords([])}}/>}
 <footer className="workspace-footer"><span>Семестр <i>·</i> Бесплатно и с открытым кодом</span><button onClick={()=>void changeTheme(theme==='dark'?'light':'dark')} aria-label="Переключить тему">{theme==='dark'?<Sun size={15}/>:<Moon size={15}/>}</button></footer></main></div>
 <aside className={'dossier '+(detailOpen?'mobile-open':'')}><div className="dossier-caption"><span className="eyebrow">ДОСЬЕ ПРЕДМЕТА</span><div><button className="icon-button" title="Редактировать предмет" disabled={!subject} onClick={()=>subject&&openEditor('subject',subject)}><Pencil size={16}/></button><button className="icon-button close-detail" aria-label="Закрыть досье" onClick={()=>setDetailOpen(false)}><X size={21}/></button></div></div>{subject?<><h2>{subject.data.title}</h2><p className="teacher">{subject.data.teacher||'Преподаватель не уточнён'}</p>{subject.data.contact&&<p className="contact"><BookOpen size={15}/>{subject.data.contact}</p>}<dl className="facts"><div><dt>Срок</dt><dd>{subjectDebts.find(activeDebt)?.data.deadline?dateLabel(subjectDebts.find(activeDebt)!.data.deadline):'Не уточнён'}</dd></div><div><dt>Аттестация</dt><dd>{labels[subject.data.assessment]}</dd></div><div><dt>Расписание</dt><dd>{subjectLessons.length?`${subjectLessons.length} занятий в серии`:'Не добавлено'}</dd></div><div><dt>Статус</dt><dd>{labels[subject.data.status]}</dd></div></dl><div className="tabs" role="tablist" aria-label="Досье предмета">{[['tasks','Задания'],['context','Контекст'],['links','Ссылки']].map(([id,label])=><button role="tab" aria-selected={tab===id} id={'tab-'+id} aria-controls={'panel-'+id} key={id} className={tab===id?'active':''} onClick={()=>setTab(id)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const ids=['tasks','context','links'];const next=ids[(ids.indexOf(id)+(e.key==='ArrowRight'?1:2))%3];setTab(next);document.getElementById('tab-'+next)?.focus()}}}>{label}</button>)}</div><div role="tabpanel" id={'panel-'+tab} aria-labelledby={'tab-'+tab} className="detail-content">
 {tab==='context'&&<>{subjectDebts.map(d=><section className="context-section" key={d.id}><div className="detail-label"><h4>{d.data.status==='clarify'?'Что нужно выяснить':labels[d.data.reason]}</h4><button className="icon-button" aria-label="Редактировать долг" onClick={()=>openEditor('debt',d)}><Pencil size={13}/></button></div><RequirementsCard text={d.data.requirements} onEdit={()=>openEditor('debt',d)}/><h4>Следующее действие</h4><button className="context-action" onClick={()=>openEditor('debt',d)}><span className={'check-square '+(d.data.status==='closed'?'checked':'')}>{d.data.status==='closed'&&<Check size={13}/>}</span>{d.data.nextStep||'Добавить конкретный шаг'}</button><div className="detail-status">{labels[d.data.status]}{d.data.confirmation&&<p>{d.data.confirmation}</p>}</div></section>)}{!subjectDebts.length&&<><h4>Условия сдачи</h4><RequirementsCard text={subject.data.requirements} onEdit={()=>openEditor('subject',subject)}/></>}{subject.data.description&&<p className="description">{subject.data.description}</p>}{subject.data.admission&&<><h4>Допуск</h4><p>{subject.data.admission}</p></>}{typed<Note>(related,'note').map(n=><button key={n.id} className="saved-note" onClick={()=>openEditor('note',n)}>{n.data.text}<Pencil size={12}/></button>)}<button className="primary wide" onClick={()=>void copyContext()}><Copy size={17}/> Скопировать контекст</button><button className="outline wide" onClick={()=>openEditor('note')}><Plus size={18}/> Добавить заметку</button></>}
 {tab==='tasks'&&<>{subjectTasks.map(taskRow)}{!subjectTasks.length&&<div className="detail-empty"><FileText size={28}/><p>Заданий пока нет.<br/>Начните с одного небольшого дела.</p></div>}<button className="outline wide" onClick={()=>openEditor('task')}><Plus size={17}/> Добавить задание</button><p className="muted small">«Отправлено» и «Принято» — разные этапы. Предмет закрывается отдельно.</p></>}
 {tab==='links'&&<>{subject.data.links.map((l,i)=><a className="link-row" key={i} href={l.url} target="_blank" rel="noreferrer"><LinkIcon size={17}/>{l.title}<ArrowUpRight size={15}/></a>)}{subjectTasks.flatMap(t=>t.data.links).map((l,i)=><a className="link-row" key={'t'+i} href={l.url} target="_blank" rel="noreferrer"><FileText size={17}/>{l.title}<ArrowUpRight size={15}/></a>)}{!subject.data.links.length&&<p className="muted">Материалы, курс и чат — соберите полезные ссылки здесь.</p>}<button className="outline wide" onClick={()=>openEditor('subject',subject)}><Plus size={17}/> Добавить ссылку</button></>}
 </div><div className="online-section"><h4>Онлайн-пара</h4>{subject.data.onlineUrl?<a className="primary wide" href={subject.data.onlineUrl} target="_blank" rel="noreferrer">Подключиться <ArrowUpRight size={17}/></a>:<button className="dashed wide" onClick={()=>openEditor('subject',subject)}><Plus size={17}/> Добавить ссылку</button>}</div><div className="schedule-detail"><div className="detail-label"><h4>Расписание</h4><button className="icon-button" aria-label="Добавить занятие" onClick={()=>openEditor('lesson')}><Plus size={15}/></button></div>{subjectLessons.map(l=><button className="lesson-mini" key={l.id} onClick={()=>openEditor('lesson',l)}><span><LessonBadge type={l.data.type}/><span className="lesson-mini-time">{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'][l.data.weekday-1]} · {l.data.startTime.slice(0,5)}–{l.data.endTime.slice(0,5)}</span><small>{labels[l.data.parity]} · {l.data.timezone}</small></span></button>)}{exceptions.filter(e=>subjectLessons.some(l=>l.id===e.lessonId)).map(e=><div className="exception-row" key={e.id}><span>{dateLabel(e.originalDate)} · {e.startsAt?'Перенос':'Отмена'}</span><button className="text-button" onClick={()=>void restoreException(e)}>Восстановить</button></div>)}{!subjectLessons.length&&<span className="muted small">Предмет можно вести без расписания.</span>}</div><button className="text-button danger delete-record" onClick={()=>demo?notify('Демоданные нельзя удалить'):setConfirmDelete(subject)}><Trash2 size={13}/> Удалить предмет</button></>:<div className="detail-empty"><BookOpen size={36} strokeWidth={1}/><h3>Вся история предмета</h3><p>Выберите предмет, чтобы увидеть задания, контекст и полезные ссылки.</p></div>}</aside>
 {editor&&<Editor {...editor} account={account} records={records} subjectId={selected||''} onClose={()=>setEditor(null)} onSaved={(message,debtSubjectId)=>{notify(message||(isLocalApp?'Сохранено на этом Mac':'Сохранено на сервере'));if(debtSubjectId){setSelected(debtSubjectId);setTab('context');setView('debts')}void refresh()}}/>}
 {confirmDelete&&<Dialog title="Удалить запись?" onClose={()=>setConfirmDelete(null)}><p>Это действие нельзя отменить. Сначала удалите связанные задания, долги, занятия и заметки — приложение защищает их от случайного удаления.</p><div className="dialog-footer"><button className="outline" onClick={()=>setConfirmDelete(null)}>Отмена</button><button className="danger-button" onClick={()=>void remove()}>Удалить</button></div></Dialog>}
 {move&&<MoveDialog occurrence={move} exception={exceptions.find(e=>e.lessonId===move.lessonId&&e.originalDate===move.originalDate)} demo={demo} onClose={()=>setMove(null)} onSaved={()=>{notify('Изменено только это занятие');void loadSchedule()}}/>}
 {notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}<button className="icon-button" aria-label="Скрыть сообщение" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 </div>
}

function MoveDialog({occurrence:o,exception,demo,onClose,onSaved}:{occurrence:Occurrence;exception?:LessonException;demo:boolean;onClose:()=>void;onSaved:()=>void}){const[mode,setMode]=useState('move');const[start,setStart]=useState('');const[end,setEnd]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function save(e:React.FormEvent){e.preventDefault();if(demo){setError('Изменения доступны после входа в свой аккаунт.');return}setBusy(true);try{await api.request(`/schedule/${o.lessonId}/exception`,'PUT',{originalDate:o.originalDate,startsAt:mode==='cancel'?null:new Date(start).toISOString(),endsAt:mode==='cancel'?null:new Date(end).toISOString(),version:exception?.version??null});onSaved();onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <Dialog title="Изменить одну пару" onClose={onClose}><p>{o.title} · {dateLabel(o.originalDate)}</p><form onSubmit={save}><label>Действие<select value={mode} onChange={e=>setMode(e.target.value)}><option value="move">Перенести</option><option value="cancel">Отменить</option></select></label>{mode==='move'&&<><p className="muted small">Новое время — в часовом поясе этого устройства.</p><label>Начало<input type="datetime-local" required value={start} onChange={e=>setStart(e.target.value)}/></label><label>Конец<input type="datetime-local" required value={end} onChange={e=>setEnd(e.target.value)}/></label></>}{error&&<div className="error" role="alert">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Сохраняем…':'Сохранить изменение'}</button></form></Dialog>}
