import {useState} from 'react';
import {ArrowUpRight,BookOpen,ArrowLeft,Mail,Leaf} from 'lucide-react';
import {api,type Account} from '@semestr/api-client';
export default function Auth({onLogin,onDemo,serverError,onRetry}:{onLogin:(a:Account)=>void;onDemo:()=>void;serverError?:string;onRetry:()=>void}){
 const hash=new URLSearchParams(location.hash.slice(1));const verify=hash.get('verify');const reset=hash.get('reset');
 const [mode,setMode]=useState(verify?'verify':reset?'reset':'login');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[error,setError]=useState('');const[message,setMessage]=useState('');const[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{
  if(mode==='login'){onLogin((await api.login(email,password)).account);return}
  if(mode==='verify'||mode==='reset'){await api.request('/auth/'+mode,'POST',{token:verify||reset,...(mode==='reset'?{password}:{})});history.replaceState(null,'',location.pathname);setMode('login');setMessage(mode==='verify'?'Почта подтверждена. Можно входить.':'Пароль обновлён. Войдите снова.');return}
  const r=await api.request<{message:string}>('/auth/'+mode,'POST',{email,...(mode==='register'?{password}:{})});setMessage(r.message);
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function change(m:string){setMode(m);setError('');setMessage('')}
 return <div className="auth-shell"><section className="auth-story"><div className="brand">Семестр<span className="brand-mark">✳</span></div><div><span className="eyebrow">ЧУТЬ МЕНЬШЕ ХАОСА. ЧУТЬ БОЛЬШЕ ЖИЗНИ.</span><h1>Учёба —<br/>по полочкам.<br/><em>Вы — спокойнее.</em></h1><p>Предметы, пары, задания и долги.<br/>Всё, что нужно, чтобы закрыть и выдохнуть.</p></div><div className="auth-bottom"><Leaf size={18}/> Бесплатно. Открытый код. Ваши данные.</div></section><section className="auth-form"><BookOpen size={30} strokeWidth={1.2}/><span className="eyebrow">ВАШЕ МЕСТО ДЛЯ УЧЁБЫ</span><h2>{{login:'С возвращением',register:'Начнём семестр',forgot:'Восстановим доступ',resend:'Новое письмо',verify:'Подтвердите почту',reset:'Новый пароль'}[mode]}</h2><p className="muted">{mode==='login'?'Войдите, чтобы продолжить с того же места.':mode==='register'?'Один аккаунт для всех ваших устройств.':mode==='verify'?'Нажмите кнопку, чтобы завершить регистрацию.':'Поможем вернуться к вашим предметам.'}</p><div className="wide">{serverError&&<div className="error" role="alert">{serverError}<button className="text-button" onClick={onRetry}>Проверить соединение</button></div>}</div><form onSubmit={submit}>{!['verify','reset'].includes(mode)&&<label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@university.ru"/></label>}{['login','register','reset'].includes(mode)&&<label>Пароль<input type="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='login'?1:12} value={password} onChange={e=>setPassword(e.target.value)} placeholder={mode==='login'?'Ваш пароль':'Минимум 12 символов'}/></label>}{error&&<div className="error" role="alert">{error}</div>}{message&&<div className="success" role="status"><Mail size={18}/>{message}</div>}<button className="primary wide" disabled={busy}>{busy?'Подождите…':{login:'Войти',register:'Создать аккаунт',forgot:'Отправить ссылку',resend:'Отправить письмо',verify:'Подтвердить email',reset:'Сохранить пароль'}[mode]}<ArrowUpRight size={18}/></button></form>{mode==='login'?<><button className="text-button" onClick={()=>change('forgot')}>Не помню пароль</button><div className="auth-switch">Первый раз здесь? <button onClick={()=>change('register')}>Создать аккаунт</button></div><button className="text-button" onClick={()=>change('resend')}>Отправить подтверждение повторно</button></>:<button className="text-button" onClick={()=>change('login')}><ArrowLeft size={15}/> Вернуться ко входу</button>}<button className="demo-link" onClick={onDemo}>Сначала посмотреть, как всё устроено <ArrowUpRight size={16}/></button></section></div>
}
