import {useEffect,useRef,useState} from 'react';
import {X,Plus,Trash2} from 'lucide-react';
import {api,isLocalApp,type Data,type StudyRecord,type Subject,type Account,type Link} from '@semestr/api-client';
import {emptyData,labels,typed} from './utils';
import DebtSubjectField from './DebtSubjectField';
import TimeField from './TimeField';
export function Dialog({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current!;el.showModal();return()=>el.close()},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="dialog-heading"><div><span className="eyebrow">ВСЁ ПО ПОЛОЧКАМ</span><h2>{title}</h2></div><button className="icon-button" aria-label="Закрыть окно" onClick={onClose}><X/></button></div>{children}</dialog>}
export default function Editor({kind,existing,subjectId,records,account,onClose,onSaved}:{kind:Data['kind'];existing?:StudyRecord;subjectId:string;records:StudyRecord[];account:Account;onClose:()=>void;onSaved:(message?:string,subjectId?:string)=>void}){
 const inlineDebt=isLocalApp&&kind==='debt'&&!existing;
 const draftKey=`semestr:draft:${account.id}:${existing?.id||kind+':'+subjectId}`;
 const readDraft=()=>{try{return JSON.parse(localStorage.getItem(draftKey)||'null')}catch{return null}};
 const [restored]=useState(()=>!!readDraft());const[baseVersion,setBaseVersion]=useState<number|undefined>(()=>readDraft()?.baseVersion??existing?.version);const[data,setData]=useState<Data>(()=>readDraft()?.data||existing?.data||emptyData(kind,subjectId,account.profile.timezone,account.profile.weekOne));const[deleting,setDeleting]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[draftError,setDraftError]=useState(false);
 const[subjectMode,setSubjectMode]=useState<'new'|'existing'>(()=>readDraft()?.subjectMode||(readDraft()?.data?.subjectId?'existing':'new'));
 const[subjectTitle,setSubjectTitle]=useState<string>(()=>readDraft()?.subjectTitle||'');
 useEffect(()=>{try{localStorage.setItem(draftKey,JSON.stringify({data,baseVersion,...(inlineDebt?{subjectMode,subjectTitle}:{})}))}catch{setDraftError(true)}},[data,draftKey,baseVersion,inlineDebt,subjectMode,subjectTitle]);
 const field=(key:string,value:unknown)=>setData(d=>({...d,[key]:value}) as Data);
 const value=(key:string)=>String((data as unknown as Record<string,unknown>)[key]??'');
 function input(label:string,key:string,type='text',required=false){return <label>{label}<input type={type} required={required} maxLength={type==='text'?300:undefined} value={value(key)} onChange={e=>field(key,e.target.value||(type==='date'?null:''))}/></label>}
 function area(label:string,key:string){return <label>{label}<textarea rows={3} maxLength={20000} value={value(key)} onChange={e=>field(key,e.target.value)}/></label>}
 function select(label:string,key:string,options:string[]){return <label>{label}<select value={value(key)} onChange={e=>field(key,e.target.value)}>{options.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select></label>}
 async function save(e:React.FormEvent){
  e.preventDefault();if(busy)return;setBusy(true);setError('');
  try{
   let debtSubjectId:string|undefined;
   if(inlineDebt&&data.kind==='debt'&&subjectMode==='new'){
    const result=await api.createDebtWithSubject(data,subjectTitle);
    debtSubjectId=result.subject.id;
   }else{
    const saved=await api.save(data,existing?{...existing,version:baseVersion??existing.version}:undefined);
    if(!existing&&saved.data.kind==='debt')debtSubjectId=saved.data.subjectId;
   }
   try{localStorage.removeItem(draftKey)}catch{/* The record is already saved. */}
   onSaved(debtSubjectId?'Долг добавлен':undefined,debtSubjectId);onClose();
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 async function reloadLatest(){if(!existing)return;try{const latest=await api.request<StudyRecord>('/records/'+existing.id);setData(latest.data);setBaseVersion(latest.version);setError('')}catch(e){setError((e as Error).message)}}
 async function remove(){if(!existing)return;setBusy(true);setError('');try{await api.request('/records/'+existing.id+'?version='+(baseVersion??existing.version),'DELETE');try{localStorage.removeItem(draftKey)}catch{/* Server save already succeeded. */}onSaved('Запись удалена');onClose()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function debtDetails(){return <>{area('Что нужно сдать','requirements')}{input('Ответственный преподаватель','teacher')}{select('Статус','status',['clarify','working','review','ready','closed'])}{value('status')==='closed'&&<>{input('Дата закрытия','closedAt','date',true)}{area('Подтверждение результата','confirmation')}</>}{value('status')!=='closed'&&value('closedAt')&&<button type="button" onClick={()=>field('closedAt',null)}>Очистить дату закрытия для возобновления</button>}{area('Заметки','notes')}</>}
 const links='links' in data?data.links:[];
 return <Dialog title={(existing?'Редактировать': 'Добавить')+' '+({subject:'предмет',task:'задание',debt:'академический долг',lesson:'занятие',note:'заметку'}[kind])} onClose={onClose}><form onSubmit={save} className="editor-form">{restored&&<div className="info">Восстановлен черновик с этого устройства.</div>}{inlineDebt&&<DebtSubjectField subjects={typed<Subject>(records,'subject')} mode={subjectMode} title={subjectTitle} subjectId={value('subjectId')} onMode={setSubjectMode} onTitle={setSubjectTitle} onSelect={id=>field('subjectId',id)}/>}
 {kind!=='subject'&&!existing&&!inlineDebt&&<label>Предмет<select required value={value('subjectId')} onChange={e=>field('subjectId',e.target.value)}><option value="">Выберите предмет</option>{typed<Subject>(records,'subject').map(s=><option key={s.id} value={s.id}>{s.data.title}</option>)}</select></label>}
 {(kind==='subject'||kind==='task')&&input('Название','title','text',true)}
 {kind==='subject'&&<><div className="form-grid">{input('Семестр','semester')}{select('Аттестация','assessment',['unknown','exam','credit','graded_credit'])}{input('Преподаватель','teacher')}{input('Контакты преподавателя','contact')}</div>{area('Описание','description')}{area('Условия сдачи','requirements')}{area('Условия допуска','admission')}{input('Ссылка на онлайн-пару','onlineUrl','url')}{select('Статус','status',['studying','ready','closed'])}</>}
 {kind==='task'&&<>{area('Описание','description')}<label>Дедлайн — в часовом поясе этого устройства<input type="datetime-local" value={data.kind==='task'&&data.deadline?new Date(new Date(data.deadline).getTime()-new Date(data.deadline).getTimezoneOffset()*60000).toISOString().slice(0,16):''} onChange={e=>field('deadline',e.target.value?new Date(e.target.value).toISOString():null)}/></label>{select('Статус','status',['todo','in_progress','submitted','accepted','revision'])}<div className="form-grid">{(['debt','lesson'] as const).map(k=><label key={k}>{k==='debt'?'Связанный долг':'Связанное занятие'}<select value={value(k+'Id')} onChange={e=>field(k+'Id',e.target.value||null)}><option value="">Не связан</option>{records.filter(r=>r.data.kind===k&&'subjectId'in r.data&&r.data.subjectId===value('subjectId')).map(r=><option key={r.id} value={r.id}>{r.data.kind==='debt'?labels[r.data.reason]:r.data.kind==='lesson'?`${r.data.startTime} · ${labels[r.data.type]}`:''}</option>)}</select></label>)}</div>{input('Ссылка на результат','resultUrl','url')}{area('Заметки','notes')}</>}
 {kind==='debt'&&<><div className="form-grid">{select('Причина','reason',['difference','overdue','retake'])}{input('Срок закрытия','deadline','date')}</div>{input('Следующий конкретный шаг','nextStep')}{inlineDebt?<details className="debt-details" open={value('status')==='closed'||undefined}><summary>Требования, преподаватель и другие детали</summary>{debtDetails()}</details>:debtDetails()}</>}
 {kind==='lesson'&&<><div className="form-grid"><label>День недели<select value={value('weekday')} onChange={e=>field('weekday',Number(e.target.value))}>{['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'].map((d,i)=><option value={i+1} key={d}>{d}</option>)}</select></label>{select('Тип','type',['lecture','practice','lab'])}<TimeField label="Начало" value={value('startTime')} onChange={v=>field('startTime',v)}/><TimeField label="Окончание" value={value('endTime')} onChange={v=>field('endTime',v)}/>{input('Первый день периода','validFrom','date',true)}{input('Последний день периода','validUntil','date',true)}</div>{input('Часовой пояс занятия (IANA)','timezone','text',true)}<div className="form-grid">{select('Повторение','parity',['all','even','odd'])}{input('Понедельник учебной недели № 1','weekOne','date',true)}</div>{input('Аудитория / место','room')}{input('Ссылка на пару','onlineUrl','url')}<p className="muted small">Если окончание раньше начала, занятие заканчивается на следующий день.</p></>}
 {kind==='note'&&area('Текст заметки','text')}
 {(kind==='subject'||kind==='task')&&<fieldset><legend>Ссылки и материалы</legend>{links.map((link,i)=><div className="link-fields" key={i}><input aria-label="Название ссылки" placeholder="Название" value={link.title} required onChange={e=>field('links',links.map((l,j)=>j===i?{...l,title:e.target.value}:l))}/><input type="url" aria-label="Адрес ссылки" placeholder="https://" value={link.url} required onChange={e=>field('links',links.map((l,j)=>j===i?{...l,url:e.target.value}:l))}/><button type="button" aria-label="Удалить ссылку" className="icon-button" onClick={()=>field('links',links.filter((_,j)=>j!==i))}><Trash2 size={16}/></button></div>)}<button type="button" className="text-button" onClick={()=>field('links',[...links,{title:'',url:''} as Link])}><Plus size={15}/> Добавить ссылку</button></fieldset>}
 {error&&<div className="error" role="alert">{error}{existing&&<button type="button" className="text-button" onClick={()=>void reloadLatest()}>Отбросить черновик и загрузить актуальную версию</button>}</div>}<div className="dialog-footer"><span className="muted small">{draftError?'Не удалось записать черновик. Не закрывайте окно.':'До сохранения текст хранится как черновик на этом устройстве.'}</span><button className="primary" disabled={busy}>{busy?'Сохраняем…':inlineDebt?'Добавить долг':'Сохранить'}</button></div>{existing&&<div className="delete-editor">{deleting?<><p className="muted">Удаление нельзя отменить. Связанные записи нужно удалить отдельно.</p><button type="button" className="danger-button" disabled={busy} onClick={()=>void remove()}>Подтвердить удаление</button><button type="button" className="text-button" onClick={()=>setDeleting(false)}>Отмена</button></>:<button type="button" className="text-button danger" onClick={()=>setDeleting(true)}><Trash2 size={14}/> Удалить запись</button>}</div>}</form></Dialog>
}
